[package]
name = "learnopengl_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glad-gl = { path = "../glad-gl" }
glam = "0.24.1"
russimp = "2.0.6"
